service: serverless-http

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          path: goodbye
          method: get
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: serverless.nareshtestdomain.tk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: arn:aws:acm:us-east-1:389442125494:certificate/9cb93a84-208c-4efa-a871-8ae1076f2b25